var webpack=require("webpack");
    // HtmlWebpackPlugin=require("html-webpack-plugin");
    module.exports={
        entry:__dirname+"/main.js",
        output:{
            path:__dirname+"/dist",//创建文件
            filename:"[name].js"//动态创建js名字
        },
        module:{
            rules:[{
                test:/\.js$/,
                loader:["babel-loader"]
            }]
        },
        devServer:{//加载器
            port:8087,
            // hot:true,
            host:"localhost",
            setup(app){
                app.get("/w",function(req,res){
                    var data=[
                        {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午11:39",
                            "xi":"[1个群有新消息]"
                        },
                         {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午12:39",
                            "xi":"[2个群有新消息]"
                        },
                         {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午13:39",
                            "xi":"[3个群有新消息]"
                        },
                         {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午1:39",
                            "xi":"[4个群有新消息]"
                        },
                         {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午2:39",
                            "xi":"[5个群有新消息]"
                        },
                         {
                            "tit":"M",
                            "tit1":"群助手",
                            "time":"上午11:39",
                            "xi":"[6个群有新消息]"
                        }
                    ];
                    res.setHeader("Access-Control-Allow-Origin","*");
                    res.setHeader("content-type","application/json;charset=utf-8")
                    res.write(JSON.stringify(data));
                    res.end()
                })
            }
        },
    }